### ISSUE TITLE
Logic Error on Date Validation

### ISSUE THREAD

**Issue by stndaru** [PBP-A07/pedulilindungi2.0#41]
I'm keeping notes here for some changes later on tonight, but there might be a bug that needs validation.

On Date Validation in `profil_penerima/views.py`, a less than sign was used to check the date.

```python
vaccine = JadwalVaksin.objects.get(penerima = penerima)

        if vaccine.tanggal < datetime.date.today():
            vaccine.delete()
```

Both vaccine.tanggal and datetime.date.today() returns the date in a string* format of DD-MM-YYYY. A possible bug might happen where python only checks based on a string and so if vaccine.tanggal is at 30-01-2020, it might still go valid even though the current date is 02-02-2020.

The solution might be to dissect the string into dates, months, and years, and check it, but haven't thought of it currently.

*might need validation and testing

**Comment by stndaru** [comment]
Current fix: 
Change the code 
```python
vaccine = JadwalVaksin.objects.get(penerima = penerima)
```
to
```python
JadwalVaksin.objects.filter(tanggal__lt=date.today()).delete()
```
And then add the code also to the root of the profile in `profil_penerima/views.py/view_profile`

**Comment by adnptrpw** [comment]
Just add this code
```python
JadwalVaksin.objects.filter(tanggal__lt=date.today()).delete()
```
to the `profil_penerima/views.py/view_profile` should be enough. There is no need to refractor other code since the intention is only for deleting the JadwalVaksin objects that have already reached their due date.
